Currently, when dependencies have the same [artifactName + version], the jar files get silently overwritten, resulting in NoClassDefFoundErrors.
It's a similar issue as here: https://github.com/GoogleContainerTools/jib/issues/3331

Fixed by adding the filesize in case of duplicates, which is still not perfect, but it is consistent with how jib itself does it.